name: Generated APK
on:
  push:
    branches: [ main ]
    
jobs:
  # Run Unit Tests etc before Generating APK here.
  # ....
    
  # A job to generate debug APK and upload on Github Artifacts
  apk:
      name: Generate APK
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v4
        - name: set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: 11.0.3

        - name: Grant Permission to Execute
          run: chmod +x gradlew

        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace

        - name: Upload APK to Github Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
